# Production
Aquatic resource production comes from the Food and Agriculture Organization (FAO), which provides national capture and aquaculture production5. The Food and Agriculture Organization provides annual capture and aquaculture production data for around 240 countries, territories, or land areas from 1950 to 2020. The FAO data reports production in tonnes (live weight equivalent) of around 550 farmed and 1600 wild capture species and species groups. FAO production data consists primarily of official national statistics, with some verifiable supplemental information from academic reviews, consultant reports, and other specialist literature. Data reported by nations are checked by the FAO for consistency and questionable values are verified with the reporting offices. When countries fail to report production, FAO uses past values to estimate production. For the purposes of this analysis, we do not distinguish between nationally reported, and FAO estimated values.

According to the Coordinating Working Party on Fishery Statistics, catch and landings should be assigned to the country of the flag flown by the fishing vessel irrespective of the location of the fishing. This means that production resulting from a country operating a fishing vessel in a foreign country's territory should be recorded in the national statistics of the foreign fishing vessel. However, if the vessel is chartered by a company based in the home country or the vessel is fishing for the country under a joint venture contract or similar agreement and the operation is integral to the economy of the host country, this does not apply. Consequently, our estimates of source country generally represent who harvested or caught the aquatic resource regardless of where it was produced (i.e., distant water fishing would generally be attributed to the flag state). In cases of exceptions related to select chartered foreign vessels, joint ventures, or other similar agreements, catch by a foreign vessel but reported by the host country may not match trade reporting if catch does not move through the customs boundary. These instances generate excess apparent consumption. 

# Bilateral trade data
We use the CEPII BACI world trade database, which is a reconciled version of the UN Comtrade database49. Trade data are reported to the UN by both importers and exporters following the Harmonized System (HS) codes. The HS trade code system organizes traded goods into a hierarchy, with the highest level represented by two-digit codes (e.g., Chapter 03 covers "Fish and Crustaceans, Molluscs and Other Aquatic Invertebrates"), which are broken down into 4-digit headings (e.g., heading 0301 covers "Live fish"), which are then subdivided into 6-digit subheadings (e.g., subheading 030111 covers "Live ornamental freshwater fish"). National statistics offices may further subdivide HS codes into 7- to 12-digit codes but since these are not standard across countries, the HS 6-digit codes are the most highly resolved trade codes available globally. HS codes are administered by the World Customs Organization, which updates the codes every five years. HS versions can be used from their introduction through the present, meaning that the HS 2002 version provides a time series of trade from 2002 to the present whereas the HS 2017 version only provides a time series back to 2017. Notably, HS version 2012 included major revisions to the HS codes relevant to fisheries and aquaculture products. 

CEPII reconciles discrepancies in mirror trade records, which occur in around 35% of observations (for all traded commodities), by first removing transportation costs and using a weighting scheme based on each country's reporting reliability to average discrepancies in reported mirror flows. BACI data focuses on trade flows between individual countries since 1994 and therefore drops flows within some groups of countries (e.g., Belgium-Luxembourg) to ensure consistent geographies. The resulting data set covers trade for over 200 countries and 5,000 products. Further details on the BACI data set are available in49. While BACI resolves many data issues contained in the raw UN Comtrade database, it does not correct for all implausible trade flows, which can especially arise if one country misreports a value and the partner country does not report a value50. Further, there are instances where one country reports on trade that is optional to report, and the partner country does not. Here, we do not identify and re-estimate any values reported in BACI. Excessively large exports will generally result in high error terms, while high imports will result in high apparent consumption.

Trade statistics are managed by each territory and generally guided by the Kyoto Convention. For the purposes of trade data reporting, imports and exports represent all goods which add or subtract, respectively, from the stock of material resources within an economic territory, but not goods which merely pass through a country’s economic territory. The economic territory generally coincides with the customs territory, which refers to the territory in which the country’s custom laws apply. Goods which enter a country for processing are included within trade statistics. Goods which pass through a country “in transit,” including those which are transshipped, are not recommended to be reported in trade statistics, though there are exceptions and known instances where one country reports trade which is “in transit” but the partner does not, which creates discrepancies that are not corrected for within BACI. Fishery products from within the country, the country’s waters, or obtained by a vessel of that country are considered goods wholly produced in that country. Catch by foreign vessels and catch by national vessels on the high seas landed in a country’s ports are recorded as imports by the country the products are landed in and as exports by the foreign nation, where economically or environmentally significant. For further trade statistic guideline details, see [International Merchandise Trade Statistics: Concepts and Definitions 2010](https://unstats.un.org/unsd/trade/eg-imts/IMTS%202010%20(English).pdf).

# Live weight conversions
Global trade data is reported in terms of the product weight. To convert from product weight (i.e., net weight) to the live weight equivalent, a live weight conversion factor must be applied for each HS code. Live weight conversion factors are sourced from the European Market Observatory for Fisheries and Aquaculture Products (EUMOFA)52, along with various national and international governmental report values. EUMOFA data reports live weight conversion factors by CN-8 codes, so the mean of the live weight conversion factors falling within each HS 6-digit code are used. The EUMOFA data assigns products primarily destined for industrial purposes (e.g., fish meal and fish oil), co-products (e.g., caviar) and live trade a value of zero. In this analysis, co-products retained a live weight conversion factor value of zero to avoid double counting, but live animal trade was assigned a live weight conversion factor of 1 and fish meal and fish oil was assigned an average value of 2.9853. Data compiled from national and international reports were categorized into taxa types (mollusks, crustaceans, fishes, and other aquatic invertebrates), FAO ISSCAAP groups, species or taxon name, type of processing, and country of processing. 

Live weight conversion factors applied to trade data introduce a source of uncertainty and error due to uncertainty in conversion factors is not reported and a single live weight conversion factor is often presented per code, regardless of the species or region of origin. This is a limitation given that there are geographical and temporal variation in live weight conversion factors due to differences in processing technology. Despite this limitation, EUMOFA data offers better documentation and alignment with HS commodity codes than other live weight conversion factor data sources18 and is updated annually, providing documentation for changes in live weight conversion factors. Additionally, by supplementing the EUMOFA data with the other reported values we can better capture specific species processing into various product forms and some regional variability. 

All conversion factors were reported as live weight to product weight ratios. These conversion factors were mapped onto possible species to commodity or commodity to commodity conversions, described below. For commodity-to-commodity conversions, we estimate the conversion factors (i.e., processing loss rate) as the additional mass lost when converting from the live weight to the original product form relative to converting from live weight to the processed product form. This can be calculated as the live weight conversion factor for the original product form divided by the live weight factor for the processed product form. We assume that mass cannot be gained through processing and therefore impose a maximum value of one to this ratio. 
Seafood production and commodity conversion
For each country-year-HS version combination, we estimate the proportion of each species going into each commodity and the proportion of each imported commodity processed into each other commodity. Each species can only be converted into a subset of the commodities. For example, Atlantic salmon, Salmo salar, can be converted into whole frozen salmon or frozen salmon filets, but cannot be converted to a frozen tilapia filet. Similarly, each commodity can only be converted to a subset of other commodities through processing. For example, whole frozen salmon can be processed into frozen salmon filets, but not vice versa and neither salmon commodity can be converted to a tilapia commodity through processing. Defining possible conversions restricts the solution space to realistic results and improves estimation by reducing the number of unknowns. We describe this assignment process in detail below. 

# Taxonomic group to commodity assignment

Species production to commodity assignment is a many-to-many matching problem, wherein one commodity can consist of multiple species and one species can be converted to multiple commodities. All taxonomic names reported in the FAO production data were matched to HS 6-digit codes based on the code descriptions and HS system hierarchy. 
The first matching step required dividing all taxonomic groups into the broad commodity groups at the 4-digit level (fish, crustaceans, molluscs and aquatic invertebrates). Within each of these groups, taxonomic groups were matched based on 6 types of matching categories:  
1.	Explicit taxa match - Scientific names are matched based on taxonomic information provided in the code description
2.	NEC match - All remaining unmatched species within the 4-digit level are assigned to the “not elsewhere considered” (NEC) code
3.	NEC by taxa match - When a code description signifies an NEC group, but limits this based on a taxonomic category (e.g., Salmonidae, N.E.C.), the NEC grouping occurs at this level, rather than the broad NEC match
4.	Broad commodity match - Only the broad taxonomic groups inform this assignment since no further taxonomic information is provided
5.	Aquarium trade match - Assigned to ornamental species trade based on species found in the aquarium/ornamental trade54
6.	Fishmeal - Assigned to fishmeal codes if at least 1% of production goes to fishmeal production globally during the study period based on the end use designation from Sea Around Us production data55. Although an estimated 27% of fishmeal is derived from processing by-products3, the species, geographical, and temporal variation in that estimate is currently unknown. Consequently, fishmeal is currently treated as sourced from whole fish reduction. This does not affect the total trade or trade patterns of fishmeal but does result in an overestimate of the proportion of production going to fishmeal in cases where by-products are used.

After all species are matched to the appropriate HS codes, we use the list of species to define codes as inland, marine, diadromous, or mixed. Higher order taxonomic groups are then only matched with HS codes that include their habitat. For example, production of inland actinopterygii is matched with codes that include inland species that fall within actinopterygii, but not with exclusively marine codes, even if they contain species that fall within actinopterygii. 

# Commodity to commodity processing assignment
As with the species to commodity assignment, the commodity-to-commodity assignment is a many-to-many data problem. Here, one commodity can be processed into multiple other commodities (i.e., frozen salmon can be processed into salmon filets or canned salmon), which also means one commodity could have come from multiple other commodities. To create these assignments, we established rules for which product transformations are technically possible. First, a product cannot transfer outside of its broad commodity group (e.g., fish, crustaceans, mollusc, aquatic invertebrate). Second, where a more refined species or species group was given (e.g., tunas, salmons, etc.) a product cannot be transformed outside that group. Third, products are classified in terms of their state (e.g., alive, fresh, frozen, etc.) and presentation (e.g., e.g., whole, fileted, salted/dried/preserved meats, reductions such as fish meal and fish oil, etc.) and cannot be converted into less processed forms (e.g., frozen salmon filets cannot turn into a frozen whole salmon). Fourth, specific commodities (i.e. mentioning specific species) and NEC commodities can become broad commodities (where appropriate), however broad commodities cannot become more specific or NEC commodities.

# Country standardization and regions
The FAO production and BACI trade datasets do not share the same set of countries and territories. For the production and trade data to balance, it is important for the set of territories falling under a given name to align across the datasets. To avoid instances where, for example, production is reported under a territory, but trade is reported under the sovereign nation, we generally group all territories with the sovereign nation. As countries gain independence, they are added as a trade partner in the database. Due to this country standardization circular flows may occur when a sovereign nation trades with their territory. These circular flows are filtered out of the standardized BACI trade flows (i.e., internal trade is not included).

Note: The original text this section is based on is from Gephart et al. (2024) *Nature Communications* [add link]. Please reference that paper when referencing this information: [Insert reference]