# Estimating Consuption

The species trade network and FAO production data were used to calculate national apparent consumption by scientific name, habitat, and method for each year. 

First, domestic production of products is estimated by multiplying production data by the corresponding estimated X matrix. We then calculate domestic consumption by subtracting domestic exports by HS code from domestic production of products. Domestic consumption by species is then derived based on the volume of domestic consumption and the estimated species composition for the associated code. 

Foreign consumption represents the quantity of product imported that was consumed in country (i.e., not subsequently exported). To calculate foreign consumption, we subtract foreign exports from the quantity of processed imports. Processed imports represent the quantity of each product, by HS code, available after accounting for processing, by multiplying the appropriate estimated W by the import vector i. We convert processed imports to live weight by multiplying by the live weight conversion factor. To distinguish human consumable products, we filter out all processed product consumption of fishmeal, fish oil and ornamental products.

Finally, we disaggregated foreign consumption of processed HS products to species. We assume the species and trade sourcing distribution of foreign consumption of a given code is proportional to the species distribution of the original imported HS products from which a final code was sourced based on the estimated species trade network. We therefore disaggregate foreign consumption by multiplying foreign consumption by the trade flow proportions of imports across all trade partners and species information.

Since apparent consumption is based on a disappearance model, estimated values are subject to multiple sources of error. Due to discrepancies in production and trade reporting for select countries (e.g., as arises with joint ventures), a few countries had unrealistically large estimated per capita consumption. For country specific consumption estimates, we capped total per capita consumption to 100 kg, as this is slightly above the upper estimate FAOSTAT25. We then adjusted the supply by export partners, scientific name, production method, habitat, and source country for those countries proportionally. A second factor that influences estimated apparent consumption relates to the approach for removing non-human consumable products, particularly the domestic production and use of fishmeal. While we base our estimates on the species mix entering HS code 230120, this is estimated based on exports and domestic use patterns could diverge, leading to errors in the volume removed. Additionally, since many species can enter code 230120 and there is limited empirical data to inform volumes of species entering fishmeal by country, there is greater uncertainty in the exact species mix, and therefore greater uncertainty in the species volumes to exclude from direct human consumption calculations.

