project: 
  type: website
  pre-render: import-external-content.R
  execute-dir: project
  
website: 
  page-navigation: true
  title: "ARTIS Manual" 
  site-url: "https://artisdata.weebly.com/" 
  repo-url: https://github.com/Seafood-Globalization-Lab/artis-manual
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with :fish [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
    
  sidebar:
    logo: "images/Lab_Logo_Full_Color_Icon.png"
    pinned: true
    align: center
    image-width: 20em
    tools: 
      - icon: globe
        href: http://seafood-globalization-lab.weebly.com/
        text: "Lab website"
      - icon: github
        href: https://github.com/Seafood-Globalization-Lab
        text: "Lab Github"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: artis-our-model/index.qmd
        contents:
          - artis-our-model/data-inputs.qmd
          - artis-our-model/est-trade-net.qmd
          - artis-our-model/est-consumption.qmd
      - section: artis-run-model/index.qmd
        contents:
          - artis-run-model/run-locally.qmd        
          - artis-run-model/run-aws.qmd
      - section: artis-infrastructure/index.qmd
        contents: 
          - artis-infrastructure/sql.qmd
          - artis-infrastructure/api.qmd
          - artis-infrastructure/archive.qmd
      - href: artis-faq.qmd
        text: FAQs

link-external-newwindow: true
link-external-filter: '^(?:http:\/\/|https:\/\/)seafood-globalization-lab\.github\.io\/artis-manual.*'


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
