
## What does it mean when a scientific name is not a true species name? 
The ARTIS model disaggregates reported aquatic resource products (e.g., frozen salmon filets) into species/species groups based on two pieces of information: 1) reported production data and 2) the lowest taxonomic resolution of the code. 

For the first piece, the mass balance portion of the model estimates the species/species group mix within each domestically-produced product code. We also estimate the processing and re-export of imported products. This allows us to estimate the share of exports sourced from domestic versus foreign production and by using the bilateral trade data, we can trace products back to the country of harvest. The species/species group mix within the code can then be assigned. Consequently, if a country  reports production of "bivalvia," then "bivalvia" will appear in the trade network. 

For the second source of taxonomic information, we look at all species that fall within a code and identify the lowest common taxonomic name. All exports identified as "error" receive this name. We also have an additional column that can be joined to ARTIS so that these names can be used in place of the model specified name when the lowest taxonomic name for the code is more detailed than the name based on the production data. Note though that if these improved names are used, domestic exports can exceed domestic production. These names (sciname_hs_modified) can be obtained for the trade data by joining the appropriate additional table by the original scientific name, the code, and the HS version. The column "sciname_hs_modified" is provided in the consumption table. 

## Why don't the trade totals match what a country reports? 
Reported trade data can (and often does) disagree across sources and it is generally not easy to determine why. These disagreements can occur at multiple levels. Some of the most common alternate data sources are bill of ladings

## How is distant water fishing captured? 

## What is the effect of underreported catch? 

## What is the effect of products in transit through an intermediate country? 

## Why are there sudden spikes?
There are two common causes of artificial spikes. The first is related to improved resolution in a country's production data. If a country previously reported production at the genus level, for example, but then starts reporting production at the species level, it could create a spike in the trade associated with the species name. In this case, one could look for a corresponding drop in the genus level data. The second reason is related to change in the HS code system. HS codes are updated every 5 years. To create a continuous time series, we default to providing

## Why are there multiple rows for a single HS product code in the code descriptions metadata file? 
Products table check why there are duplicates (usually caused by multiple presentations or states associated with one code, 030719, H5 probably HS12, 20 codes with 2 states or duplicates). 
Need to remove duplicates when joining. 